# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard
service: backendv2
runtime: custom
env: flex

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 10

