# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard
service: backendv2
runtime: custom
env: flex

resources:
  cpu: 4
  memory_gb: 2
  disk_size_gb: 4

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1


