# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard
service: backendv2
runtime: custom
env: flex

env_variables:
  SPRING_PROFILES_ACTIVE: prod

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1


